name: Compile

env:
  CGO_ENABLED: 1

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

jobs:
  compile:
    runs-on: ${{ inputs.os }}
    strategy:
      fail-fast: false
      matrix:
        arch: [amd64, arm64]
    
    env:
      GOARCH: ${{ matrix.arch }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.0
      
      - name: Compile application
        run: |
          go build -o "main-${{ inputs.os }}" main.go 

      - name: Preserve build artifact
        uses: actions/upload-artifact@v3
        with:
          name: main-${{ inputs.os }}
          path: main-${{ inputs.os }}